/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesLeadershipAdvisoryRouteImport } from './routes/services.leadership-advisory'
import { Route as ServicesExecutiveSearchRouteImport } from './routes/services.executive-search'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeadershipAdvisoryRoute =
  ServicesLeadershipAdvisoryRouteImport.update({
    id: '/leadership-advisory',
    path: '/leadership-advisory',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesExecutiveSearchRoute = ServicesExecutiveSearchRouteImport.update({
  id: '/executive-search',
  path: '/executive-search',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/leadership-advisory': typeof ServicesLeadershipAdvisoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/leadership-advisory': typeof ServicesLeadershipAdvisoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/leadership-advisory': typeof ServicesLeadershipAdvisoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/services'
    | '/services/executive-search'
    | '/services/leadership-advisory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/services'
    | '/services/executive-search'
    | '/services/leadership-advisory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/services'
    | '/services/executive-search'
    | '/services/leadership-advisory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/leadership-advisory': {
      id: '/services/leadership-advisory'
      path: '/leadership-advisory'
      fullPath: '/services/leadership-advisory'
      preLoaderRoute: typeof ServicesLeadershipAdvisoryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/executive-search': {
      id: '/services/executive-search'
      path: '/executive-search'
      fullPath: '/services/executive-search'
      preLoaderRoute: typeof ServicesExecutiveSearchRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesExecutiveSearchRoute: typeof ServicesExecutiveSearchRoute
  ServicesLeadershipAdvisoryRoute: typeof ServicesLeadershipAdvisoryRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesExecutiveSearchRoute: ServicesExecutiveSearchRoute,
  ServicesLeadershipAdvisoryRoute: ServicesLeadershipAdvisoryRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
